/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as MelhoriasRouteImport } from './routes/melhorias'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EstatisticasRouteImport } from './routes/estatisticas'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FaqIndexRouteImport } from './routes/faq.index'
import { Route as FaqStatsRouteImport } from './routes/faq.stats'
import { Route as FaqAdminUsersRouteImport } from './routes/faq.admin.users'
import { Route as FaqAdminImprovementsRouteImport } from './routes/faq.admin.improvements'
import { Route as FaqAdminChatsRouteImport } from './routes/faq.admin.chats'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const MelhoriasRoute = MelhoriasRouteImport.update({
  id: '/melhorias',
  path: '/melhorias',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatisticasRoute = EstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqIndexRoute = FaqIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FaqRoute,
} as any)
const FaqStatsRoute = FaqStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => FaqRoute,
} as any)
const FaqAdminUsersRoute = FaqAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => FaqRoute,
} as any)
const FaqAdminImprovementsRoute = FaqAdminImprovementsRouteImport.update({
  id: '/admin/improvements',
  path: '/admin/improvements',
  getParentRoute: () => FaqRoute,
} as any)
const FaqAdminChatsRoute = FaqAdminChatsRouteImport.update({
  id: '/admin/chats',
  path: '/admin/chats',
  getParentRoute: () => FaqRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/estatisticas': typeof EstatisticasRoute
  '/faq': typeof FaqRouteWithChildren
  '/melhorias': typeof MelhoriasRoute
  '/usuarios': typeof UsuariosRoute
  '/faq/stats': typeof FaqStatsRoute
  '/faq/': typeof FaqIndexRoute
  '/faq/admin/chats': typeof FaqAdminChatsRoute
  '/faq/admin/improvements': typeof FaqAdminImprovementsRoute
  '/faq/admin/users': typeof FaqAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/estatisticas': typeof EstatisticasRoute
  '/melhorias': typeof MelhoriasRoute
  '/usuarios': typeof UsuariosRoute
  '/faq/stats': typeof FaqStatsRoute
  '/faq': typeof FaqIndexRoute
  '/faq/admin/chats': typeof FaqAdminChatsRoute
  '/faq/admin/improvements': typeof FaqAdminImprovementsRoute
  '/faq/admin/users': typeof FaqAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/estatisticas': typeof EstatisticasRoute
  '/faq': typeof FaqRouteWithChildren
  '/melhorias': typeof MelhoriasRoute
  '/usuarios': typeof UsuariosRoute
  '/faq/stats': typeof FaqStatsRoute
  '/faq/': typeof FaqIndexRoute
  '/faq/admin/chats': typeof FaqAdminChatsRoute
  '/faq/admin/improvements': typeof FaqAdminImprovementsRoute
  '/faq/admin/users': typeof FaqAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chats'
    | '/estatisticas'
    | '/faq'
    | '/melhorias'
    | '/usuarios'
    | '/faq/stats'
    | '/faq/'
    | '/faq/admin/chats'
    | '/faq/admin/improvements'
    | '/faq/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chats'
    | '/estatisticas'
    | '/melhorias'
    | '/usuarios'
    | '/faq/stats'
    | '/faq'
    | '/faq/admin/chats'
    | '/faq/admin/improvements'
    | '/faq/admin/users'
  id:
    | '__root__'
    | '/'
    | '/chats'
    | '/estatisticas'
    | '/faq'
    | '/melhorias'
    | '/usuarios'
    | '/faq/stats'
    | '/faq/'
    | '/faq/admin/chats'
    | '/faq/admin/improvements'
    | '/faq/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatsRoute: typeof ChatsRoute
  EstatisticasRoute: typeof EstatisticasRoute
  FaqRoute: typeof FaqRouteWithChildren
  MelhoriasRoute: typeof MelhoriasRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/melhorias': {
      id: '/melhorias'
      path: '/melhorias'
      fullPath: '/melhorias'
      preLoaderRoute: typeof MelhoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estatisticas': {
      id: '/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof EstatisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/': {
      id: '/faq/'
      path: '/'
      fullPath: '/faq/'
      preLoaderRoute: typeof FaqIndexRouteImport
      parentRoute: typeof FaqRoute
    }
    '/faq/stats': {
      id: '/faq/stats'
      path: '/stats'
      fullPath: '/faq/stats'
      preLoaderRoute: typeof FaqStatsRouteImport
      parentRoute: typeof FaqRoute
    }
    '/faq/admin/users': {
      id: '/faq/admin/users'
      path: '/admin/users'
      fullPath: '/faq/admin/users'
      preLoaderRoute: typeof FaqAdminUsersRouteImport
      parentRoute: typeof FaqRoute
    }
    '/faq/admin/improvements': {
      id: '/faq/admin/improvements'
      path: '/admin/improvements'
      fullPath: '/faq/admin/improvements'
      preLoaderRoute: typeof FaqAdminImprovementsRouteImport
      parentRoute: typeof FaqRoute
    }
    '/faq/admin/chats': {
      id: '/faq/admin/chats'
      path: '/admin/chats'
      fullPath: '/faq/admin/chats'
      preLoaderRoute: typeof FaqAdminChatsRouteImport
      parentRoute: typeof FaqRoute
    }
  }
}

interface FaqRouteChildren {
  FaqStatsRoute: typeof FaqStatsRoute
  FaqIndexRoute: typeof FaqIndexRoute
  FaqAdminChatsRoute: typeof FaqAdminChatsRoute
  FaqAdminImprovementsRoute: typeof FaqAdminImprovementsRoute
  FaqAdminUsersRoute: typeof FaqAdminUsersRoute
}

const FaqRouteChildren: FaqRouteChildren = {
  FaqStatsRoute: FaqStatsRoute,
  FaqIndexRoute: FaqIndexRoute,
  FaqAdminChatsRoute: FaqAdminChatsRoute,
  FaqAdminImprovementsRoute: FaqAdminImprovementsRoute,
  FaqAdminUsersRoute: FaqAdminUsersRoute,
}

const FaqRouteWithChildren = FaqRoute._addFileChildren(FaqRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatsRoute: ChatsRoute,
  EstatisticasRoute: EstatisticasRoute,
  FaqRoute: FaqRouteWithChildren,
  MelhoriasRoute: MelhoriasRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
